config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  devise_scope :user do
    namespace :api, defaults: {format: 'json'} do
      post '/login' => 'sessions#create'
    end
  end
  resources :tv_shows
  namespace :api, defaults: {format: 'json'} do
    resources :tv_shows
    resources :tv_show_statistics, only: [:index, :edit, :show]
  end

end

app/models/tv_show.rb
class TvShow < ActiveRecord::Base
  validates :code, presence: true
  validates :name, presence: true
  validates :url, presence: true
  validates :tv_show_type, presence: true
  validates :language, presence: true
  validates :status, presence: true
end

app/models/tv_show_statistic.rb
class TvShowStatistic < ActiveRecord::Base
  validates :category, presence: true
  validates :statistic_type, presence: true
end

app/models/user.rb
class User < ActiveRecord::Base
  USER_ROLES = %w(ADMIN USER)

  validates :username, presence: true
  validates :email, presence: true
  validates :password, presence: true, length: { in: 8..128 }, if: :new_record?
  validates :role, presence: true, inclusion: { in: USER_ROLES }

  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable
end

app/controllers/api/sessions_controller.rb
module Api
  class SessionsController < ::Devise::SessionsController
    skip_before_action :require_no_authentication, only: [:create]
    skip_before_action :verify_signed_out_user, only: [:destroy]

    def create
      resource = User.find_by(username: params[:username])
      raise "Invalid username" if resource.nil?

      password_valid = resource.valid_password?(params[:password])
      raise "Invalid password" unless password_valid

      resource.update_attribute :authn_token, SecureRandom.hex

      payload = {username: resource.username, authn_token: resource.authn_token}
      token = JWT.encode payload, nil, 'none'

      render text: {token: token}.to_json
    end
  end
end

app/controllers/api/tv_show_statistics_controller.rb
module Api
  class TvShowStatisticsController < ApplicationController
    before_action :set_tv_show_statistic, only: [:show, :edit]
    before_action :authenticate_user_from_token!

    def index
      @tv_show_statistics = TvShowStatistic.all
      render json: @tv_show_statistics
    end

    def show
      render json: @tv_show_statistic
    end

    def edit
      render json: @tv_show_statistic
    end
    private
      def set_tv_show_statistic
        @tv_show_statistic = TvShowStatistic.find(params[:id])
      end

      def authenticate_user_from_token!
        token = params[:token]
        raise "Invalid Token" unless token.present?
        decoded_token = JWT.decode token, nil, false
        raise "Invalid Token" unless decoded_token.present?
        hsh = decoded_token[0]
        user = User.find_by(username: hsh['username'])
        raise "Invalid Token" unless user.present?
        raise "Invalid Token" unless user.authn_token == hsh['authn_token']
      end
  end
end

app/controllers/api/tv_shows_controller.rb
module Api
  class TvShowsController < ApplicationController
    before_action :set_tv_show, only: [:show, :edit, :update, :destroy]
    before_action :authenticate_user_from_token!, only: [:create, :update, :destroy]

    def index
      @tv_shows = TvShow.all
      render json: @tv_shows
    end

    def show
      render json: @tv_show
    end

    def edit
      render json: @tv_show
    end

    def new
      @tv_show = TvShow.new
      render json: @tv_show
    end

    def create
      @tv_show = TvShow.new(tv_show_params)
      @tv_show.save!

      render json: @tv_show
    end

    def update
      @tv_show.update!(tv_show_params)
      render json: @tv_show
    end

    def destroy
      @tv_show.destroy!

      render text: {message: "Record sucessfully deleted"}.to_json
    end
    private
      def set_tv_show
        @tv_show = TvShow.find(params[:id])
      end

      def tv_show_params
        params.require(:data).permit(:code, :name, :url, :tv_show_type, :language, :status, :runtime)
      end

      def authenticate_user_from_token!
        token = params[:token]
        raise "Invalid Token" unless token.present?
        decoded_token = JWT.decode token, nil, false
        raise "Invalid Token" unless decoded_token.present?
        hsh = decoded_token[0]
        user = User.find_by(username: hsh['username'])
        raise "Invalid Token" unless user.present?
        raise "Invalid Token" unless user.authn_token == hsh['authn_token']
        raise "Not Authorize User" unless user.role == "ADMIN"
      end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :null_session
  rescue_from ::RuntimeError, with: :runtime_error

  def runtime_error(e)
    render text: {error_message: e.to_s}.to_json
  end
end

app/controllers/tv_shows_controller.rb
class TvShowsController < ApplicationController
  before_action :set_tv_show, only: [:show, :edit, :update, :destroy]

  # GET /tv_shows
  # GET /tv_shows.json
  def index
    @tv_shows = TvShow.all
  end

  # GET /tv_shows/1
  # GET /tv_shows/1.json
  def show
  end

  # GET /tv_shows/new
  def new
    @tv_show = TvShow.new
  end

  # GET /tv_shows/1/edit
  def edit
  end

  # POST /tv_shows
  # POST /tv_shows.json
  def create
    @tv_show = TvShow.new(tv_show_params)

    respond_to do |format|
      if @tv_show.save
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully created.' }
        format.json { render :show, status: :created, location: @tv_show }
      else
        format.html { render :new }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /tv_shows/1
  # PATCH/PUT /tv_shows/1.json
  def update
    respond_to do |format|
      if @tv_show.update(tv_show_params)
        format.html { redirect_to @tv_show, notice: 'Tv show was successfully updated.' }
        format.json { render :show, status: :ok, location: @tv_show }
      else
        format.html { render :edit }
        format.json { render json: @tv_show.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /tv_shows/1
  # DELETE /tv_shows/1.json
  def destroy
    @tv_show.destroy
    respond_to do |format|
      format.html { redirect_to tv_shows_url, notice: 'Tv show was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_tv_show
      @tv_show = TvShow.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def tv_show_params
      params.require(:tv_show).permit(:id, :name, :url, :tv_show_type, :language, :status, :runtime)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/tv_shows_helper.rb
module TvShowsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>CodingChallenge</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/tv_shows/_form.html.erb
<%= form_for(@tv_show) do |f| %>
  <% if @tv_show.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@tv_show.errors.count, "error") %> prohibited this tv_show from being saved:</h2>

      <ul>
      <% @tv_show.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :id %><br>
    <%= f.text_field :id %>
  </div>
  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :url %><br>
    <%= f.text_field :url %>
  </div>
  <div class="field">
    <%= f.label :tv_show_type %><br>
    <%= f.text_field :tv_show_type %>
  </div>
  <div class="field">
    <%= f.label :language %><br>
    <%= f.text_field :language %>
  </div>
  <div class="field">
    <%= f.label :status %><br>
    <%= f.text_field :status %>
  </div>
  <div class="field">
    <%= f.label :runtime %><br>
    <%= f.number_field :runtime %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/tv_shows/edit.html.erb
<h1>Editing Tv Show</h1>

<%= render 'form' %>

<%= link_to 'Show', @tv_show %> |
<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Tv Shows</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>Name</th>
      <th>Url</th>
      <th>Tv show type</th>
      <th>Language</th>
      <th>Status</th>
      <th>Runtime</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @tv_shows.each do |tv_show| %>
      <tr>
        <td><%= tv_show.id %></td>
        <td><%= tv_show.name %></td>
        <td><%= tv_show.url %></td>
        <td><%= tv_show.tv_show_type %></td>
        <td><%= tv_show.language %></td>
        <td><%= tv_show.status %></td>
        <td><%= tv_show.runtime %></td>
        <td><%= link_to 'Show', tv_show %></td>
        <td><%= link_to 'Edit', edit_tv_show_path(tv_show) %></td>
        <td><%= link_to 'Destroy', tv_show, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Tv show', new_tv_show_path %>

app/views/tv_shows/new.html.erb
<h1>New Tv Show</h1>

<%= render 'form' %>

<%= link_to 'Back', tv_shows_path %>

app/views/tv_shows/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Id:</strong>
  <%= @tv_show.id %>
</p>

<p>
  <strong>Name:</strong>
  <%= @tv_show.name %>
</p>

<p>
  <strong>Url:</strong>
  <%= @tv_show.url %>
</p>

<p>
  <strong>Tv show type:</strong>
  <%= @tv_show.tv_show_type %>
</p>

<p>
  <strong>Language:</strong>
  <%= @tv_show.language %>
</p>

<p>
  <strong>Status:</strong>
  <%= @tv_show.status %>
</p>

<p>
  <strong>Runtime:</strong>
  <%= @tv_show.runtime %>
</p>

<%= link_to 'Edit', edit_tv_show_path(@tv_show) %> |
<%= link_to 'Back', tv_shows_path %>